# Generated by Django 2.2 on 2019-05-08 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='scraping_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_files', models.CharField(blank=True, max_length=100, null=True)),
                ('in_progress_files', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
